apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAidXNlcm5hbWUiOiAiZ3JhbnRhc3Npc3QiLA0KICAgICAgInBhc3N3b3JkIjogImdocF8yNkJ1WE82RFVJNnZlRjVsamFQbkphZnhYcWd3R2czcDBZSDUiDQogICAgfQ0KICB9DQp9DQo=
type: kubernetes.io/dockerconfigjson